volumes:
  postgres:

services:
  postgres:
    image: timescale/timescaledb-ha:pg14-latest
    container_name: rastercar-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: raster_user
      POSTGRES_PASSWORD: raster_pass
    ports:
      - "5432:5432"
    privileged: true
    volumes:
      - ../env:/initdb-env
      - postgres:/var/lib/postgresql/data

  rabbitmq:
    container_name: rastercar-rmq
    image: rabbitmq:3.10.1-management
    ports:
      - 5672:5672
      - 15672:15672

  jaeger:
    container_name: rastercar-jaeger
    image: "jaegertracing/all-in-one:latest"
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
